options:
  logging: NONE  # Disable logging
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/flask-redis-app-web:$SHORT_SHA'
      - '.'

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/flask-redis-app-web:$SHORT_SHA'

  # Step 3: Deploy to Kubernetes Engine
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/flask-web'
      - 'flask-web=gcr.io/$PROJECT_ID/flask-redis-app-web:$SHORT_SHA'
      - '--namespace=default'

images:
  - 'gcr.io/$PROJECT_ID/flask-redis-app-web:$SHORT_SHA'
