apiVersion: v1
kind: Service
metadata:
  name: flask-web
spec:
  type: LoadBalancer
  selector:
    app: flask-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080   # 👈 This was 5000 before